import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Toaster } from "sonner"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        {children}
        <Toaster />
        <footer className="bg-[#1A1B1F] px-5 py-6">
          <p className="text-sm text-gray-400">
            © 2023 Copyright <strong>FSW Barber</strong>
          </p>
        </footer>
      </body>
    </html>
  )
}
